src/config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('courses/', include('courses.urls')),
    path('', include('courses.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/courses/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('course/<int:pk>', CourseDetail.as_view(), name='course_detail'),
    path('course/<int:course_id>/theme/<int:pk>', ThemeDetail.as_view(), name='theme_detail'),
    path('course/<int:course_id>/theme/<int:theme_id>/task/<int:task_id>', TaskDetail.as_view(), name='task_detail'),
]

src/courses/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class Course(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    student = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return self.title


class Theme(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Task(models.Model):
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


TYPE_CHOICES = (
    ('MultipleChoice', 'Multiple Choice'),
    ('ExactMatch', 'Exact Match'),
    ('Var', 'Variants'),
)


class Quiz(models.Model):
    type = models.CharField(max_length=100, choices=TYPE_CHOICES, default='Var')
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

    def __str__(self):
        return self.content


class QuizMultipleChoice(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

    def __str__(self):
        return self.content


class QuizExactMatch(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    answer = models.CharField(max_length=100)

    def __str__(self):
        return self.content


class QuizVar(models.Model):
    test = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ['content']


class QuizMultipleChoiceVar(models.Model):
    quiz = models.ForeignKey(QuizMultipleChoice, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ['content']



class Lecture(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = RichTextUploadingField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

src/courses/forms.py
from django import forms
from .models import Task, Quiz, QuizVar, Lecture


# create a form for test
def create_test_form():
    tests = Quiz.objects.all()
    test_form = []
    for test in tests:
        test_var = test.testvar_set.all()
        test_form.append((test.id, test.content, test_var))
    return test_form


    # l = ((1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'))

    # class TestForm(forms.Form):
    #     choice = forms.ChoiceField(choices=l, widget=forms.RadioSelect)
    #
    # return TestForm

src/courses/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, View
from .models import Course, Theme, Task, Quiz
from django.core.paginator import Paginator


from .forms import create_test_form


def index(request):
    if request.user.is_authenticated:
        courses = Course.objects.filter(student=request.user)
        return render(request, 'courses/index.html', {'courses': courses})
    else:
        return render(request, 'courses/index.html')


class CourseDetail(DetailView):
    model = Course
    template_name = 'courses/course_detail.html'


class ThemeDetail(DetailView):
    model = Theme
    template_name = 'courses/theme_detail.html'


class TaskDetail(View):
    def post(self, request, course_id, theme_id, task_id):
        response = check_test_results(request, task_id)
        return response

    def get(self, request, course_id, theme_id, task_id):
        task = Task.objects.get(id=task_id)
        lectures = task.lecture_set.all()
        quizes = task.quiz_set.all()
        quizes_multiple_choice = task.quizmultiplechoice_set.all()
        is_quiz_page = request.GET.get('quiz', 0)
        lecture_page = get_lecture_page(request, lectures)
        is_paginated = bool(lecture_page)
        return render(request, 'courses/task_detail.html', {'task': task,
                                                            'lecture_page': lecture_page,
                                                            'lectures': lectures,
                                                            'quizes': quizes,
                                                            'quizes_multiple_choice': quizes_multiple_choice,
                                                            'is_quiz_page': is_quiz_page,
                                                            'is_paginated': is_paginated})


def get_lecture_page(request, lectures):
    if lectures:
        paginator = Paginator(lectures, 1)
        lecture_num = request.GET.get('lecture', 1)
        lecture_page = paginator.get_page(lecture_num)
        return lecture_page
    else:
        return None


def check_test_results(request, task_id):
    task = Task.objects.get(id=task_id)
    quizes = task.test_set.all()
    quizes_multi = task.quizmultiplechoice_set.all()
    results = []
    if quizes:
        check_quiz_choice(quizes)
    if quizes_multi:
        check_quiz_choice(quizes_multi)
    return render(request, 'courses/test_result.html', {'results': results})


def check_quiz_choice(quizes):  # QuerySet
    for quiz in quizes:
        quizvar_id = request.POST.get(str(quiz.id))
        quiz_var = quiz.testvar_set.get(id=quizvar_id)
        if quiz_var.is_correct:
            results.append('Correct')
        else:
            results.append('Incorrect')

src/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}English{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body>
<div class="opacity-75">
    <nav class="navbar bg-primary navbar-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">CourseMastery</a>
            <div class="d-flex">
                {% if user.is_authenticated %}
                    <div class="btn-group">
                        <a role="button" href="{% url 'index' %}" type="button" class="btn btn-primary" style="background-color: #0f7bca;">
                            {{ user.username }}</a>
                        <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split"
                                data-bs-toggle="dropdown" aria-expanded="false" style="background-color: #0f7bca;">
                            <span class="visually-hidden">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'logout' %}?next={{ request.path }}"
                                   class="dropdown-item">Logout</a></li>
                        </ul>
                    </div>
                    {% if user.is_staff %}
                        <div class="container">
                            <a role="button" href="{% url 'admin:index' %}" class="btn btn-danger">Admin</a>
                        </div>
                    {% endif %}
                {% else %}
                    <a href="{% url 'login' %}?next={{ request.path }}"
                       class="btn btn-primary">Login</a>
                {% endif %}

                </div>
            </div>
    </nav>
</div>
<div class="container-lg mt-5">
    <div>
        {% block content %}
            No content
        {% endblock %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

src/templates/courses/course_detail.html
{% extends 'base.html' %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">My courses</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ course.title }}</li>
        </ol>
    </nav>
    <h1>{{ course.title }}</h1>
    <p>{{ course.description }}</p>
    {% for theme in course.theme_set.all %}
        <div class="card" style="width: 40rem; margin-bottom: 2rem;">
            <div class="card-body">
                <h5 class="card-title">{{ theme.title }}</h5>
                <p class="card-text">{{ theme.description }}</p>
                <a href="{% url 'theme_detail' course.id theme.id %}" class="btn btn-primary">Go to theme</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}

src/templates/courses/img_upload.html
{% extends 'base.html' %}

{% block content %}
    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
{% endblock %}

src/templates/courses/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Courses{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <h3>Мої курси:</h3>
        <div class="mt-3">
            {% for course in courses %}
            <div class="card" style="width: 25rem;">
                <img src="{% static 'images/learning.png' %}" class="card-img-top" alt="Course cover">
                <div class="card-body">
                    <h5 class="card-title">{{ course.title }}</h5>
                    <p class="card-text">{{ course.description }}</p>
                    <a href="{% url 'course_detail' course.id %}" class="btn btn-primary">Go to course</a>
                </div>
            </div>
        {% endfor %}
        </div>

    {% else %}
        <p>Ви не авторизовані</p>
    {% endif %}
{% endblock %}

src/templates/courses/task_detail.html
{% extends 'base.html' %}

{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">My courses</a></li>
            <li class="breadcrumb-item"><a href="{% url 'course_detail' task.theme.course.id %}">{{ task.theme.course.title }}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'theme_detail' task.theme.course.id task.theme.id %}">{{ task.theme.title }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ task.title }}</li>
        </ol>
    </nav>

    <h3> {{ task.title }} </h3>
    <p>{{ task.description}} </p>

    {% if is_paginated %}
        <ul class="nav nav-tabs">
            {% for lecture in lectures %}
                <li class="nav-item">
                    <a class="nav-link {% if lecture_page.number == forloop.counter and not is_test %}active{% endif %}"
                       href="?lecture={{ forloop.counter }}">{{ lecture.title }}</a>
                </li>

            {% endfor %}
            <li class="nav-item">
                <a class="nav-link {% if is_quiz_page %}active{% endif %}"
                   href="?quiz=1">Test</a>
            </li>
        </ul>

        {% if task.lecture_set.count > 0 and not is_quiz_page %}
            {% with lecture=lecture_page.0  %}
                <div class="mt-10">
                    <div class="container">
                        <h4>{{ lecture.title }}</h4>
                        <p>{{ lecture.content|safe }}</p>
                    </div>
                </div>
            {% endwith %}

        {% else %}
            {% if quizes or quizes_multiple_choice %}
                <form method="post">
                    {% csrf_token %}

                    {% if quizes %}
                        {% for quiz in quizes %}
                            <div class="mb-3">
                                <p>{{ forloop.counter }}. {{ quiz.content }}</p>
                                {% for quizvar in quiz.quizvar_set.all %}
                                    <div>
                                        <input type="radio" id="{{ quizvar.id }}"
                                               value="{{ quizvar.id }}"
                                               name="{{ quiz.id }}">
                                        <label for="{{ quizvar.id }}">{{ quizvar.content }}</label>
                                    </div>
                                {% endfor %}
                            </div>
                        {% endfor %}
                    {% endif %}

                    {% if quizes_multiple_choice%}
                        {% for quiz in quizes_multiple_choice %}
                            <div class="mt-3">
                                <p>{{ forloop.counter }}. {{ quiz.content }}</p>
                                {% for quizvar in quiz.quizmultiplechoicevar_set.all %}
                                    <div>
                                        <input type="checkbox" id="{{ quizvar.id }}"
                                               value="{{ quizvar.id }}"
                                               name="{{ quiz.id }}">
                                        <label for="{{ quizvar.id }}">{{ quizvar.content }}</label>
                                    </div>
                                {% endfor %}
                            </div>

                        {% endfor %}

                    {% endif %}
                <input class="btn btn-primary mt-3" type="submit" value="Send">
            </form>

            {% endif %}
        {% endif %}
    {% endif %}

{% endblock %}

src/templates/courses/test_result.html
{% extends 'base.html' %}

{% block content %}
    {% for result in results %}
        <p>{{ forloop.counter }}. {{ result}}</p>
    {% endfor %}

{% endblock %}

src/templates/courses/theme_detail.html
{% extends 'base.html' %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">My courses</a></li>
            <li class="breadcrumb-item"><a href="{% url 'course_detail' theme.course.id %}">{{ theme.course.title }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ theme.title }}</li>
        </ol>
    </nav>
    <h2>{{ theme.title }}</h2>
    {% for task in theme.task_set.all %}
        <div class="mt-5">
            <div class="card" style="width: 25rem;">
                <div class="card-body">
                    <h5 class="card-title">{{ task.title }}</h5>
                    <p class="card-text">{{ task.description }}</p>
                    <a href="{% url 'task_detail' theme.course.id theme.id task.id %}" class="btn btn-primary">Go to task</a>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}